
import { BREAKPOINTS as BP } from '@constants/breakpoints';

export const BREAKPOINTS = BP;

export const RESIZE_CONFIG = {
  JITTER_TOLERANCE: 8,
} as const;

export const SCROLL_CONFIG = {
  HEADER_OFFSET: 80,
  SMOOTH_DURATION: 1000,
  THROTTLE_MS: 16,
  SCROLL_DETECTION_THRESHOLD: 10,
  SECTION_THRESHOLD: 100,
  HEADER_OFFSET_SCROLL: -50,
} as const;

export const ANIMATION_TIMING = {
  FAST: 100,
  NORMAL: 150,
  SLOW: 200,
  VERY_SLOW: 300,
} as const;

export const NAVIGATION_TIMING = {
  MENU_CLOSE_DELAY: 300,
  NAV_DELAY: 100,
  SCROLL_THRESHOLD: 50,
} as const;

export const SWIPE_CONFIG = {
  MIN_HORIZONTAL_DISTANCE: 15,
  HORIZONTAL_VERTICAL_RATIO: 3,
  SWIPE_THRESHOLD: 50,
  VELOCITY_THRESHOLD: 0.5,
  ANIMATION_DURATION: 300,
  MIN_TOUCH_DURATION: 10,
  USER_ACTION_WINDOW: 500,
} as const;

export const INTERSECTION_OBSERVER_CONFIG = {
  THRESHOLD: 0.5,
  ROOT_MARGIN_BOTTOM: '-50%',
} as const;
